apiVersion: v1
kind: Service
metadata:
  name: amenities-overpass-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: amenities-overpass-proxy-service-port
    protocol: TCP
  selector:
    app: amenities-overpass-proxy
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: amenities-overpass-proxy
  labels:
    app: amenities-overpass-proxy
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: amenities-overpass-proxy
  template:
    metadata:
      labels:
        app: amenities-overpass-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: amenities-overpass-proxy
        image: registry.mnt.ee/peatusee/amenities-overpass-proxy:latest
        imagePullPolicy: Always
        command:
        - npm
        args:
        - start
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 10
          httpGet:
            port: 8080
            path: /
      imagePullSecrets:
      - name: peatusee
