apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-default-service-port
  selector:
    app: digitransit-ui-default
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-default
  labels:
    app: digitransit-ui-default
    update: auto
    restartAt: "03.20_13.20"
    restartLimitInterval: "180"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-default
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: digitransit-ui-default
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-default
        image: registry.mnt.ee/peatusee/digitransit-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "estonia"
        - name: API_URL
          value: "https://api.ENVIROMENT.peatus.ee"
        - name: ASSET_URL
          value: "https://api.ENVIROMENT.peatus.ee/ui/v1/estonia"
        - name: MAP_URL
          value: "https://api.ENVIROMENT.peatus.ee"
        - name: NODE_OPTS
          value: "--max_old_space_size=1000"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: OTP_URL
          value: "https://api.ENVIROMENT.peatus.ee/routing/v1/routers/estonia/"
        - name: GEOCODING_BASE_URL
          value: "https://api.ENVIROMENT.peatus.ee/geocoding/v1"
        - name: VEHICLES_URL
          value: "wss://mqtt.ENVIROMENT.peatus.ee:443"
        - name: PIWIK_ADDRESS
          value: ""
        - name: PIWIK_ID
          value: ""
        - name: PORT
          value: "8080"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-dsn
              key: sentry-dsn
        - name: SENTRY_SECRET_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-secret-dsn
              key: sentry-secret-dsn
        resources:
          requests:
            memory: "1536Mi"
            cpu: 600m
          limits:
            memory: "1536Mi"
            cpu: 2000m
      imagePullSecrets:
      - name: peatusee

