apiVersion: v1
kind: Service
metadata:
  name: digitransit-proxy
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: digitransit-proxy-service-port
    protocol: TCP
  selector:
    app: digitransit-proxy
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-proxy
  labels:
    app: digitransit-proxy
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: digitransit-proxy
  template:
    metadata:
      labels:
        app: digitransit-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-proxy
        image: registry.mnt.ee/peatusee/digitransit-proxy:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 10
          httpGet:
            port: 8080
            path: /
        env:
        - name: OLD_LISSU_BASIC_AUTH
          value: default
        - name: JOJO_BASIC_AUTH
          value: default
        - name: LINKKIU_BASIC_AUTH
          value: default
        - name: VILKKU_BASIC_AUTH
          value: default
        - name: NEW_LISSU_BASIC_AUTH
          value: default
        - name: LAPPEENRANTA_BASIC_AUTH
          value: default
      imagePullSecrets:
      - name: peatusee
