apiVersion: v1
kind: Service
metadata:
  name: gtfs-rt-server
spec:
  ports:
  - port: 18080
    targetPort: 3333
    name: gtfs-rt-server-service-port
    protocol: TCP
  selector:
    app: gtfs-rt-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-rt-server
  labels:
    app: gtfs-rt-server
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gtfs-rt-server
  template:
    metadata:
      labels:
        app: gtfs-rt-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: gtfs-rt-server
        image: registry.mnt.ee/peatusee/gtfs-rt-server:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 3333
        env:
        - name: OTP_URL
          value: "http://opentripplanner-estonia:8080/otp/routers/estonia/index/graphql"
        - name: MQTTCLIENTURL
          value: "mqtt://mosquitto-server:1883"
        - name: MQTTCLIENTUSER
          value: "publisher"
        - name: MQTTCLIENTPASS
          value: "sHalLnoTpaSS"
      imagePullSecrets:
      - name: peatusee
