apiVersion: v1
kind: Service
metadata:
  name: hsl-map-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: hsl-map-server-service-port
    protocol: TCP
  selector:
    app: hsl-map-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsl-map-server
  labels:
    app: hsl-map-server
    update: auto
    restartAfterDeployments: "opentripplanner-hsl_opentripplanner-waltti" #TODO include finland when we figure out best way to circumvent label length restriction
    restartDelay: "5"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: hsl-map-server
  template:
    metadata:
      labels:
        app: hsl-map-server  
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: hsl-map-server
        image: registry.mnt.ee/peatusee/hsl-map-server:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /map/v1/hsl-map/index.json
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
          httpGet:
            port: 8080
            path: /map/v1/hsl-map/index.json
        env:
          - name: ESTONIA_OTP_URL
            value: "opentripplanner-estonia:8080/otp/routers/estonia/index/graphql/"
          - name: FONTSTACK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fontstack-password
                key: fontstack-password
          - name: NODE_OPTS
            value: "--max_old_space_size=2048 --optimize_for_size --stack_size=2048 --harmony"
          - name: MAPSERVER_URL
            value: "hsl-map-server:8080/map/v1/"
        resources:
          requests:
            memory: 4096Mi
            cpu: 2000m
          limits:
            memory: 4096Mi
            cpu: 4000m
      imagePullSecrets:
      - name: peatusee

