apiVersion: v1
kind: Service
metadata:
  name: mosquitto-server
spec:
  ports:
  - port: 1883
    targetPort: 1883
    name: mosquitto-server-service-port1
    protocol: TCP
  - port: 9001
    targetPort: 9001
    name: mosquitto-server-service-port2
    protocol: TCP
  selector:
    app: mosquitto-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-server
  labels:
    app: mosquitto-server
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mosquitto-server
  template:
    metadata:
      labels:
        app: mosquitto-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: mosquitto-server
        image: registry.mnt.ee/peatusee/mosquitto-server:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports: 
        - containerPort: 1883
        - containerPort: 9001
      imagePullSecrets:
      - name: peatusee

