apiVersion: v1
kind: Service
metadata:
  name: pelias-placeholder
spec:
  ports:
  - port: 4100
    targetPort: 4100
    name: pelias-placeholder-service-port
    protocol: TCP
  selector:
    app: pelias-placeholder
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-placeholder
  labels:
    app: pelias-placeholder
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pelias-placeholder
  template:
    metadata:
      labels:
        app: pelias-placeholder
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: pelias-placeholder
        image: registry.mnt.ee/peatusee/pelias-placeholder:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 4100
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "4100"
      imagePullSecrets:
      - name: peatusee

